# Generated by Django 4.2.1 on 2023-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user_id', models.CharField(max_length=30)),
                ('tos_1', models.CharField(max_length=1)),
                ('tos_2', models.CharField(max_length=1)),
                ('tos_opt_1', models.CharField(max_length=1, null=True)),
                ('tos_opt_2', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'terms_agreement',
            },
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
