# Generated by Django 3.2.25 on 2024-07-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_terms_agreement_alter_members_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Terms_agreement',
        ),
        migrations.RemoveField(
            model_name='members',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='members',
            name='duck',
        ),
        migrations.RemoveField(
            model_name='members',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='members',
            name='level_figure',
        ),
        migrations.RemoveField(
            model_name='members',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='members',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user_img',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user_level',
        ),
        migrations.AddField(
            model_name='members',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='user_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='user_pw',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
